### PR TITLE
Add 'rename' option to allow renaming of existing notes

### PR DESCRIPTION
**Pull request by mromerdagan**

### CODE REVIEW

**Comment by TicklishHoneyBee** [comment]
In the man page you've missed 'an' from the description for rename (line 45) "rename existing note" -> "rename an existing note" (it's correct in the help output).

Renaming an encrypted note will decrypt it, without the user knowing. It should either:
1. warn the user that the note will be decrypted, with the option to cancel.
2. move the note without decrypting.
3. give the user an option to encrypt it or not.

**Comment by mromerdagan** [comment]
Hi @TicklishHoneyBee , thanks for your comments.
Made another push that includes:
1. Fix grammar error in man page
2. Use DB update to perform renaming: Simpler implementation that will keep encryption if exists

**Comment by TicklishHoneyBee** [comment]
Ok, something I didn't notice till I actually tried it out, is that now `rename' requires the arguments to be encapsulated in "quotes" if there's a space in the note's name. This makes it the only operation that requires this:

`nodau create something new' is valid
`nodau edit something new' is valid
`nodau rename something new something else' is not valid, `nodau rename "something new" "something else"' is valid

I'm not sure how to change this, or if it should be changed, but the discrepancy is bugging me.

**Comment by mromerdagan** [comment]
You are correct, arguments are separated by spaces in 'rename'. However, I don't think it's much of a problem- this is compliant with POSIX standard. 
Take 'ls' for example- if given two words separated with space, they will be considered as two distinct arguments. Quotes around them will mark them as one argument that has space in it. Another syntax is to use '\ ' as space (for exeample: my\ file)

I can, if you want, issue another PR to make this behavior common to all supported actions (for uniformity)

Waiting to hear what you think. If there any change that can mitigate the pain around this I'd like to hear about it.

**Comment by TicklishHoneyBee** [comment]
Not delimiting on space was a deliberate decision which I'd rather not change if possible. Which leaves us with a couple of options:

1. Leave it as is, but add a note to the man page's SEARCH TERM section that spaces do affect the rename operation.
2. Make rename only take one argument, and then prompt for the new name.
3. Something else, I'm open to other ideas.

**Comment by mromerdagan** [comment]
I'd go with option 1, but of course it's your call.
Another option to consider is use flags for rename. For example:

    $ nodau rename -o old name -n new name

Would search for existing note named 'old name', and rename it to 'new name'.

So, whatever you decide. Please let me know.

**Comment by TicklishHoneyBee** [comment]
Yeah, simple is good. If you can add a comment/note to the manpage, I'll consider that done.

**Pull request merged**
